### Get all 
GET http://localhost:3000/products
### Get by id
GET http://localhost:3000/products/2


### Create
POST http://localhost:3000/users/login
Content-Type: application/json

{

  
   "email": "patolucas@example.com",
   "password": "password124",
   "rol": "admin"
   

}

### Update
PUT http://localhost:3000/users/6
Content-Type: application/json

{
    "name": "Paca",
   "email": "paca@example.com",
   "password": "password124",
   "rol": "admin",
   "status":"1"
    
}

### Delete
DELETE http://localhost:3000/products/5